name: build and push

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: 'Version of the image to build'
        type: string
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.MACHINE_GITHUB_USER }}
          password: ${{ secrets.MACHINE_GITHUB_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/arm64/v8,linux/amd64
          file: Dockerfile
          tags: ghcr.io/aidan-port/port-aws-cost-exporter:${{ inputs.VERSION }},ghcr.io/aidan-port/port-aws-cost-exporter:latest
